// Sport sections (catalog of disciplines).
export type RgccSection = {
  clubId: "rgcc";
  id: string;
  name: string;
  category: "Equipo" | "Individual" | "Acuático" | "Combate" | "Cultural" | "Mente" | "Outdoor";
  responsible: string;
  membersCount: number;
  venueLabel: string;
  description: string;
};

export const RGCC_SECTIONS: RgccSection[] = [
  {
    clubId: "rgcc",
    id: "ajedrez",
    name: "Ajedrez",
    category: "Mente",
    responsible: "Iván Solís",
    membersCount: 84,
    venueLabel: "Las Mestas",
    description: "Sección histórica con torneos y formación.",
  },
  {
    clubId: "rgcc",
    id: "atletismo",
    name: "Atletismo",
    category: "Individual",
    responsible: "Lucía Pérez",
    membersCount: 312,
    venueLabel: "Las Mestas",
    description: "Pruebas de pista, ruta y campo a través.",
  },
  {
    clubId: "rgcc",
    id: "baloncesto",
    name: "Baloncesto",
    category: "Equipo",
    responsible: "Marcos Rivero",
    membersCount: 268,
    venueLabel: "Las Mestas",
    description: "Equipos en categorías de base y senior.",
  },
  {
    clubId: "rgcc",
    id: "balonmano",
    name: "Balonmano",
    category: "Equipo",
    responsible: "Eva Tuñón",
    membersCount: 156,
    venueLabel: "Las Mestas",
    description: "Competición autonómica y nacional.",
  },
  {
    clubId: "rgcc",
    id: "billar",
    name: "Billar",
    category: "Mente",
    responsible: "Jorge Bao",
    membersCount: 42,
    venueLabel: "Begoña",
    description: "Salas y modalidades libre y carambola.",
  },
  {
    clubId: "rgcc",
    id: "bolos",
    name: "Bolos",
    category: "Cultural",
    responsible: "Manuel Rúa",
    membersCount: 38,
    venueLabel: "Las Mestas",
    description: "Bolo asturiano, tradición viva.",
  },
  {
    clubId: "rgcc",
    id: "boxeo",
    name: "Boxeo",
    category: "Combate",
    responsible: "Diego Ramos",
    membersCount: 124,
    venueLabel: "Begoña",
    description: "Iniciación, técnica y competición amateur.",
  },
  {
    clubId: "rgcc",
    id: "coros-danzas",
    name: "Coros y Danzas",
    category: "Cultural",
    responsible: "Pilar Acebal",
    membersCount: 96,
    venueLabel: "Las Mestas",
    description: "Folclore asturiano y representación.",
  },
  {
    clubId: "rgcc",
    id: "diversidad-funcional",
    name: "Diversidad Funcional",
    category: "Cultural",
    responsible: "Ana Suárez",
    membersCount: 64,
    venueLabel: "Las Mestas",
    description: "Programas inclusivos multidisciplinares.",
  },
  {
    clubId: "rgcc",
    id: "esqui",
    name: "Esquí",
    category: "Outdoor",
    responsible: "Pablo Roces",
    membersCount: 178,
    venueLabel: "Las Mestas",
    description: "Salidas a Pajares y competición FIS.",
  },
  {
    clubId: "rgcc",
    id: "gaf",
    name: "GAF",
    category: "Individual",
    responsible: "Carla Méndez",
    membersCount: 142,
    venueLabel: "Las Mestas",
    description: "Gimnasia Artística Femenina.",
  },
  {
    clubId: "rgcc",
    id: "gam",
    name: "GAM",
    category: "Individual",
    responsible: "Hugo Lago",
    membersCount: 98,
    venueLabel: "Las Mestas",
    description: "Gimnasia Artística Masculina.",
  },
  {
    clubId: "rgcc",
    id: "halterofilia",
    name: "Halterofilia",
    category: "Individual",
    responsible: "Sergio Caso",
    membersCount: 72,
    venueLabel: "Begoña",
    description: "Levantamientos olímpicos.",
  },
  {
    clubId: "rgcc",
    id: "hockey",
    name: "Hockey",
    category: "Equipo",
    responsible: "Nuria Vega",
    membersCount: 188,
    venueLabel: "Las Mestas",
    description: "Hockey hierba, base y senior.",
  },
  {
    clubId: "rgcc",
    id: "judo",
    name: "Judo",
    category: "Combate",
    responsible: "Andrés Coto",
    membersCount: 134,
    venueLabel: "Begoña",
    description: "Cinturones desde blanco a negro.",
  },
  {
    clubId: "rgcc",
    id: "karate",
    name: "Kárate",
    category: "Combate",
    responsible: "Lara Ibáñez",
    membersCount: 118,
    venueLabel: "Begoña",
    description: "Kata y kumite, todas las edades.",
  },
  {
    clubId: "rgcc",
    id: "lucha",
    name: "Lucha",
    category: "Combate",
    responsible: "Iker Solana",
    membersCount: 56,
    venueLabel: "Begoña",
    description: "Lucha grecorromana y libre.",
  },
  {
    clubId: "rgcc",
    id: "montana",
    name: "Montaña",
    category: "Outdoor",
    responsible: "Olaya Pando",
    membersCount: 224,
    venueLabel: "Las Mestas",
    description: "Senderismo, alpinismo y BTT.",
  },
  {
    clubId: "rgcc",
    id: "natacion",
    name: "Natación",
    category: "Acuático",
    responsible: "Gema Ríos",
    membersCount: 412,
    venueLabel: "Las Mestas",
    description: "Aprendizaje, perfeccionamiento y competición.",
  },
  {
    clubId: "rgcc",
    id: "orfeon",
    name: "Orfeón",
    category: "Cultural",
    responsible: "Ramón Cifuentes",
    membersCount: 72,
    venueLabel: "Las Mestas",
    description: "Coro polifónico del club.",
  },
  {
    clubId: "rgcc",
    id: "padel",
    name: "Pádel",
    category: "Individual",
    responsible: "Bea Lombardía",
    membersCount: 286,
    venueLabel: "Mareo",
    description: "Liga interna y escuela técnica.",
  },
  {
    clubId: "rgcc",
    id: "pelota",
    name: "Pelota",
    category: "Individual",
    responsible: "Xabi Olano",
    membersCount: 48,
    venueLabel: "Las Mestas",
    description: "Pelota mano y paleta.",
  },
  {
    clubId: "rgcc",
    id: "piraguismo",
    name: "Piragüismo",
    category: "Acuático",
    responsible: "Marta Cienfuegos",
    membersCount: 92,
    venueLabel: "Playa",
    description: "Aguas tranquilas y travesías.",
  },
  {
    clubId: "rgcc",
    id: "rugby",
    name: "Rugby",
    category: "Equipo",
    responsible: "Tom Fielding",
    membersCount: 198,
    venueLabel: "Mareo",
    description: "Equipos masculino, femenino y base.",
  },
  {
    clubId: "rgcc",
    id: "surf",
    name: "Surf",
    category: "Acuático",
    responsible: "Jana Ardura",
    membersCount: 112,
    venueLabel: "Playa",
    description: "Escuela y entrenamiento de competición.",
  },
  {
    clubId: "rgcc",
    id: "tenis",
    name: "Tenis",
    category: "Individual",
    responsible: "Roberto Pin",
    membersCount: 264,
    venueLabel: "Mareo",
    description: "Pistas de tierra batida y dura.",
  },
  {
    clubId: "rgcc",
    id: "tiro-arco",
    name: "Tiro con Arco",
    category: "Individual",
    responsible: "Inés Bárcena",
    membersCount: 38,
    venueLabel: "Las Mestas",
    description: "Recurvo y compuesto, sala y aire libre.",
  },
  {
    clubId: "rgcc",
    id: "vela",
    name: "Vela",
    category: "Acuático",
    responsible: "Borja Estrada",
    membersCount: 86,
    venueLabel: "Playa",
    description: "Optimist, Láser y travesías.",
  },
  {
    clubId: "rgcc",
    id: "voleibol",
    name: "Voleibol",
    category: "Equipo",
    responsible: "Sara Cabal",
    membersCount: 124,
    venueLabel: "Las Mestas",
    description: "Equipos absolutos y categorías base.",
  },
];
